server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "docker-logs"
    pipeline_stages:
      - docker: {}  # ✅ Enable Docker log parsing
    static_configs:
      - targets:
          - localhost
        labels:
          job: "fastapi"
          __path__: /var/lib/docker/containers/*/*-json.log